blank_issues_enabled: false
contact_links:
  - name: Project Documentation (Wiki)
    url: https://github.com/Graswald-Schaetzle/cosmic-webapp-frontend/wiki
    about: Technical documentation, setup guides and architecture overview
